/**
 * @runstamp/docx
 *
 * JSON-first DOCX rendering engine.
 * DocxDocument JSON in, .docx binary out.
 *
 * No React. No DOM. No Puppeteer. No browser.
 *
 * @example
 * ```ts
 * import { renderToDocx } from '@runstamp/docx';
 *
 * const result = await renderToDocx({
 *   type: 'DocxDocument',
 *   pageSize: 'a4',
 *   pages: [{
 *     elements: [
 *       { type: 'heading', level: 1, text: 'Hello World' },
 *       { type: 'paragraph', text: 'Generated by an AI agent.' },
 *     ]
 *   }]
 * });
 *
 * fs.writeFileSync('output.docx', result.buffer);
 * ```
 */

// =============================================================================
// PRIMARY API
// =============================================================================

import * as pvceRaw from '@runstamp/pvce';

type DocxPvce = Record<string, unknown> & {
  compileChart: (...args: unknown[]) => unknown;
  chartToSVG: (...args: unknown[]) => unknown;
};

export {
  renderToDocx,
  renderToDocxWithQuality,
  renderToPdf,
  hydrateDocxToPdf,
  renderWithTrackedChanges,
  renderHtmlToDocx,
  hydrateDocx,
  validateDocxDocument,
} from './render.js';
export {
  setDeterministicMode,
  isDeterministicModeEnabled,
} from './deterministic-mode.js';
export {
  DEFAULT_DOCX_ARCHIVE_LIMITS,
  DOCX_CONTROLLED_DOCUMENT_MANIFEST,
  DOCX_CONTROLLED_LOSS_CODES,
  DOCX_CONTROLLED_WARNING_CODES,
  DocxControlledDocumentError,
  applyDocxRedactions,
  createDocxControlledDocumentExtension,
  exportControlledDocx,
  findControlledDocx,
  importControlledDocx,
  inspectControlledDocx,
  previewDocxRedactions,
  verifyControlledDocx,
} from './controlled-document/index.js';
export type {
  ControlledDocxDocument,
  ControlledDocxPart,
  DocxArchiveLimits,
  DocxControlledErrorCode,
  DocxControlledInspection,
  DocxFindResult,
  DocxRedactionPreview,
  DocxRedactionProof,
  DocxRedactionResult,
  DocxRelationshipInspection,
  DocxTextLocator,
  DocxTrackedChangeVisibility,
  DocxVerificationReport,
  DocxVerifyIssue,
} from './controlled-document/index.js';
export { validateDocxWithReferenceApplication } from './controlled-document/reference-validator.js';
export type {
  DocxReferenceApplication,
  DocxReferenceValidationResult,
} from './controlled-document/reference-validator.js';
export {
  DOCX_RELAXED_INPUT_COERCIONS,
  preprocessDocxDocumentInput,
} from './relaxed-input.js';
export {
  validateDocxBuffer,
  DocxStrictValidationError,
} from './core/ooxml-output-validator.js';
export type {
  OoxmlValidationIssue,
  OoxmlValidationResult,
} from './core/ooxml-output-validator.js';
export {
  DocxQualityGate,
  runDocxQualityGate,
} from './quality/index.js';
export type {
  DocxExpectedSemanticManifest,
  DocxQualityGateArtifactHashes,
  DocxQualityGateInput,
  DocxQualityGateManifest,
  DocxQualityGateResult,
  DocxQualityGateSidecars,
  DocxRenderStatsForQualityGate,
} from './quality/index.js';

// =============================================================================
// HIGH-LEVEL BUILDERS (Mode B convenience)
// =============================================================================
// These builders mirror the MCP wrapper shapes (`generate_report_docx`,
// `generate_invoice_docx`, `generate_contract_docx`) so a JSON spec written
// against the MCP server can be rendered locally with one call:
//
//   const doc = buildReportDocx({ title: '...', sections: [...] });
//   const result = await renderToDocx(doc);
//
// They produce canonical `DocxDocument` JSON — the same value the renderer
// accepts directly — so you can post-process the spec before rendering.
export {
  buildReportDocx,
  buildInvoiceDocx,
  buildContractDocx,
} from './builders/index.js';
export type {
  BuildReportDocxInput,
  BuildInvoiceDocxInput,
  BuildContractDocxInput,
  InvoiceParty,
  InvoiceLineItem,
  ContractParty,
  ContractClause,
  ContractSignature,
} from './builders/index.js';
export type {
  FindingCode,
  QualityFinding,
  QualityReport,
  QualityVerdict,
  RenderWithQualityResult,
  RepairEntry,
  RepairRisk,
} from './quality/types.js';
export { diffDocxDocuments } from './diff/document-diff.js';
export { compareDocuments } from './diff/compare-documents.js';
export type { Change, ChangeSet, DiffOptions } from './diff/document-diff.js';
export type {
  CompareDocumentsOptions,
  CompareDocumentsResult,
} from './diff/compare-documents.js';

// =============================================================================
// SCHEMA (for AI agents and MCP tools)
// =============================================================================

export {
  DocxDocumentSchema,
  DocxElementSchema,
  TextRunSchema,
  CommentInfoSchema,
  HeadingElementSchema,
  ParagraphElementSchema,
  ListElementSchema,
  TableElementSchema,
  ImageElementSchema,
  ChartElementSchema,
  ShapeElementSchema,
  CodeBlockElementSchema,
  PageBreakElementSchema,
  DividerElementSchema,
  DocxPageSchema,
  DocxThemeSchema,
  DocxTemplateSchema,
  HeaderFooterDefSchema,
  BaseStyleSchema,
  BorderStyleSchema,
  SpacingSchema,
  ColorValue,
  RevisionInfoSchema,
  type DocxDocument,
  type DocxElement,
  type DocxPage,
  type DocxTheme,
  type DocxTextRun,
  type DocxRevisionInfo,
  type HeaderFooterDef,
  TableOfContentsSchema,
  HtmlDocxOptionsSchema,
  type HtmlDocxOptions,
} from './schema.js';

// =============================================================================
// TYPES
// =============================================================================

export type {
  // Result types
  DocxResult,
  PdfResult,
  RenderStats,
  DocxWarning,
  RenderOptions,
  RevisionInfo,
  TextRunRevision,
  TextRunStyleSnapshot,
  RenderProgress,
  ValidationResult,
  ValidationIssue,
  DocxInputWarning,
  HydrationOptions,

  // Adapter interfaces
  ImageAdapter,
  ChartAdapter,
  ChartRenderInput,

  // Internal types (for advanced use / custom adapters)
  TableOfContentsConfig,
  StructuredDocument,
  StructuredPage,
  StructuredElement,
  DocumentMetadata,
  PageDimensions,
  ElementType,
  BaseElement,
  HeadingElement,
  ParagraphElement,
  TextRunElement,
  TableElement,
  ImageElement,
  ChartElement,
  ShapeElement,
  ListElement,
  ContainerElement,
  TableColumn,
  TableRow,
  TableCell,
  CellReference,
  CellStyle,
  TextRun,
  CommentInfo,
  ComputedStyle,
  BoundingBox,
  BorderStyle,
  FillStyle,
  GradientDefinition,
  GradientStop,
  StrokeStyle,
  ExtractedLayoutInfo,
  DOCXHints,
  SectionBreak,
  HeaderFooterContent,
  Background,
  AssetRegistry,
  StyleDefinitions,
  ExtractionStats,
  ChartType,
  ChartSeries,
  ShapeType,
  ListItem,
  LegendConfig,
  AxesConfig,
  AxisConfig,
} from './types.js';

// =============================================================================
// ERROR SYSTEM
// =============================================================================

export {
  DOCXError,
  DOCXErrorCode,
  DOCXWarningCode,
  Errors,
  Warnings,
  WarningCollector,
  isDOCXError,
  toDOCXError,
  createWarning,
  formatWarning,
} from './errors.js';

export {
  WARNING_CODES,
  isDocxWarningCode,
  resolveDocxWarningCode,
  type DocxWarningCode,
} from './errors/warning-codes.js';

export {
  serializeStructuredToNativeOOXML,
  type NativeOOXMLSerializerOptions,
  type NativeOOXMLSerializerResult,
} from './ooxml/native-serializer.js';

// =============================================================================
// ADAPTER (for custom input formats)
// =============================================================================

export { docxToStructured } from './adapters/docx-to-structured.js';
export { paperToStructured } from './adapters/paper-to-structured.js';
export { convertHtmlToStructured } from './adapters/html-to-structured.js';
export type { HtmlConversionOptions } from './adapters/html-to-structured.js';
export type { PaperDocumentInput } from './adapters/paper-types.js';

// =============================================================================
// UTILITIES
// =============================================================================

export {
  pxToTwips,
  pointsToHalfPoints,
  inchesToTwips,
  inchesToEmu,
  pxToEmu,
  mmToTwips,
  lineHeightToDocx,
  PAGE_SIZES,
  pxToHalfPoints,
  // Branded unit types (Phase 1.1): opt-in type safety for callers
  // that want compile-time unit-confusion detection.
  asTwips,
  asHalfPoints,
  asEmu,
  asPoints,
  asPx,
  asInches,
  asMm,
  asLineSpacingDxa,
  type Twips,
  type HalfPoints,
  type EMU,
  type Points,
  type Px,
  type Inches,
  type Mm,
  type LineSpacingDxa,
} from './utils/units.js';

export {
  isCodeBlock,
  detectImageAlignment,
  isMonospaceFont,
} from './utils/detection.js';

// =============================================================================
// THEMES & TEMPLATES
// =============================================================================

export {
  getThemePreset,
  getDefaultTheme,
  CORPORATE_THEME,
  MODERN_THEME,
  ACADEMIC_THEME,
  CLASSIC_THEME,
  MINIMAL_THEME,
  DARK_THEME,
  type Theme,
  type ThemePresetName,
} from './themes/presets.js';

// =============================================================================
// HYDRATION
// =============================================================================

export {
  hydrateTemplate,
} from './hydration/hydrator.js';
export type {
  HydrationArchiveLimits,
  HydrationImageLimits,
} from './hydration/hydrator.js';

export {
  scanForPlaceholders,
} from './hydration/placeholder-scanner.js';

// =============================================================================
// BATCH GENERATION
// =============================================================================

export { batchRender, batchHydrate } from './batch.js';

export { BatchOptionsSchema } from './schema.js';

export type { BatchOptions, BatchResult, BatchItemResult } from './types.js';

// =============================================================================
// PVCE CHARTING ENGINE
// =============================================================================

const pvce: DocxPvce = {
  ...(pvceRaw as Record<string, unknown>),
  compileChart(...args: unknown[]) {
    return pvceRaw.compileChart(...args as Parameters<typeof pvceRaw.compileChart>);
  },
  chartToSVG(...args: unknown[]) {
    return pvceRaw.chartToSVG(...args as Parameters<typeof pvceRaw.chartToSVG>);
  },
};

export { pvce };

// =============================================================================
// CORE ENGINE UTILITIES
// =============================================================================

export * as core from './core/index.js';

// =============================================================================
// EXPERIMENTAL SURFACES
// =============================================================================

export * as experimental from './experimental/index.js';

// =============================================================================
// SECURE PDF
// =============================================================================

export { SecurePDF } from './secure/index.js';

// =============================================================================
// ACCESSIBILITY
// =============================================================================

export { validateAccessibility, remediateAccessibility } from './accessibility/index.js';
export type {
  AccessibilityReport,
  AccessibilityViolation,
  AccessibilityLevel,
  DocxAccessibilityViolationCode,
} from './accessibility/types.js';
export type { AccessibilityRemediationResult } from './accessibility/remediator.js';

// =============================================================================
// COMPLIANCE VALIDATION
// =============================================================================

export {
  IndiaGSTQRSchema,
  EUReverseChargeSchema,
  BrazilianDanfeSchema,
  validateIndiaGSTQR,
  validateEUReverseCharge,
  validateBrazilianDanfe,
} from './compliance/index.js';
